apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: backend
spec:
  selector:
    app: portfolio-react #label of the pod
  ports:
    - protocol: TCP
      port: 8000 #port of the service
      targetPort: 8000 #port of the pod
  type: LoadBalancer #expose the service to the internet